README.md, factgenie/cli.py, factgenie/config.yml, factgenie/evaluate.py, factgenie/llm-eval/ollama-qwen2-logicnlg.yaml, factgenie/main.py, factgenie/outputs/logicnlg/test/GPT4-direct-2shotCoT.json, factgenie/utils.py
Maybe it is easier to view the changes commit by commit (except the first wip commit 😅 )
=> add llm-eval, documenting and testing LLM evaluation

factgenie/main.py, factgenie/templates/crowdsourcing.html, factgenie/templates/llm_eval.html
=> Add an option for exporting annotations

factgenie/main.py, factgenie/templates/campaigns/closed.html, factgenie/utils.py
=> User-friendly page for no more crowdsourcing examples

factgenie/main.py
=> Fix: crowdsourcing URL was not displayed correctly behind reverse proxy

factgenie/main.py
Reporting error in json instead
=> fix returning non-existent variable after exception.

factgenie/loaders/logicnlg.py, factgenie/static/js/factgenie.js
=> WIP: formatted outputs in browsing mode plus numbers for logicnlg

factgenie/loaders/datasets.yml, factgenie/loaders/logicnlg.py, factgenie/outputs/logicnlg/test/GPT4-direct-2shotCoT.json
fix also formatting
replaces #91
=> fix input ids and output generation mismatch for logicNLG

factgenie/loaders/basic.py, factgenie/loaders/logicnlg.py
=> Naive fix for #116

factgenie/loaders/dataset.py, factgenie/static/js/factgenie.js, factgenie/templates/index.html, factgenie/templates/llm_campaign_new.html, factgenie/templates/manage.html, factgenie/utils.py
=> Fix: Compute the number of outputs based on available outputs

factgenie/bin/run.py
Tested with
```
factgenie download -d easy-vqa
factgenie download -d quintd1-ice-hockey
```
Also added extension of `factgenie list` to see all available datasets to be downloaded
```
$ factgenie list downloadable
2024-11-13 09:18:59 INFO run.py:341 Application ready
easy-vqa - downloaded: True
logicnlg-100 - downloaded: True
quintd1-gsmarena - downloaded: True
quintd1-ice-hockey - downloaded: True
quintd1-openweather - downloaded: False
quintd1-owid - downloaded: False
quintd1-wikidata - downloaded: False
xsum-debug - downloaded: False
```
=> Download dataset cli

factgenie/analysis.py, factgenie/app.py, factgenie/bin/run.py, factgenie/config/config_TEMPLATE.yml, factgenie/static/css/custom.css, factgenie/static/js/config.js, factgenie/templates/pages/app_config.html, factgenie/templates/pages/index.html
Add "Public browse mode": a way to run a limited instance of factgenie where only browsing existing examples is allowed.
Running demo available here: https://quest.ms.mff.cuni.cz/nlg/d2t-llm/
Resolves https://github.com/ufal/factgenie/issues/59
=> Add public mode

factgenie/datasets/propaganda_techniques.py, factgenie/static/js/browse.js, factgenie/templates/pages/browse.html
Add an option to display badges with letters of error categories
=> Add annotation badges

factgenie/static/js/manage.js, factgenie/templates/pages/manage.html, factgenie/workflows.py
Fix incorrect output caching and incorrect deletion process
=> Fix output management

factgenie/campaign.py, factgenie/crowdsourcing.py, factgenie/models.py, factgenie/static/js/annotate.js, factgenie/static/js/span-annotator.js, factgenie/workflows.py
A set of minor fixes mostly related to crowdsourced annotations.
=> Annotation interface fixes

factgenie/config/default_prompts.yml, factgenie/static/js/span-annotator.js
=> Enable removing annotations with right mouse button

factgenie/static/js/annotate.js, factgenie/static/js/span-annotator.js
Hopefully provides a solution for #187 , although needs to be confirmed.
=> Fix glitches in annotation UI

factgenie/datasets/rotowire_shared_task.py
- Adding days of the week
- Adding total wins & losses in the season
- Adding explicit indicators for which team is home and which is away
=> Small tweaks to Rotowire presentation

factgenie/analysis.py
Previously, we computed a **modified version of gamma score** accounting for empty examples.
However, this turned out to make the score more convoluted, without making it more useful 🙃
Therefore, we are now computing:
- `gamma_score`: the original gamma score as computed by [pygamma-agreement](https://github.com/bootphon/pygamma-agreement). This gets computed for outputs where we have >=2 non-empty annotation sets.
- `s_empty_score`: a supplementary score computed as `1/(1 + |A|)` (`|A|` being the size of the remaining annotation set, 0 in case it is missing). This gets computed for outputs where we have <2 non-empty annotation sets.
=> Separate computation of gamma score and s_empty_score

factgenie/bin/run.py
Info and error logs are merged together for better continuity.
=> Merge logging

factgenie/bin/run.py
Add logic for handling extra arguments for the `factgenie run` command.
`--host-prefix` can be now specified as an argument, which resolves #230
=> Extra arguments for the `run` command

factgenie/llm_campaign.py, factgenie/prompting/strategies/eval_default.py, factgenie/prompting/strategies/eval_raw_output.py, factgenie/prompting/strategies/eval_sentence_split.py, factgenie/prompting/transforms.py, factgenie/static/js/campaigns.js, factgenie/templates/pages/llm_campaign_new.html
=> Enforce annotation granularity (words / chars) for LLMs
